baseUrl = "https://dyagan.github.io/"
title = "Danny Yagan"
author = "UC Berkeley Opportunity Lab"
canonifyurls = false
languagecode = "en"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Danny Yagan"
  subheading = "UC Berkeley Economics"
  disableWebFonts = false

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 5
[[menu.main]]
    name = "Press"
    url = "/press/"
    weight = 6
