baseurl = "https://www.example.com/"
title = "Danny Yagan"
author = "UC Berkeley Opportunity Lab"
canonifyurls = true
languagecode = "en"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Prof. Danny Yagan"
  subheading = "UC Berkeley Economics"
  disableWebFonts = false

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "Bio"
    url = "/bio/index.html"
    weight = 2
[[menu.main]]
    name = "Research"
    url = "/research/index.html"
    weight = 3
[[menu.main]]
    name = "Data"
    url = "/data/index.html"
    weight = 4
[[menu.main]]
    name = "Teaching"
    url = "/teaching/index.html"
    weight = 5
[[menu.main]]
    name = "Press"
    url = "/press/index.html"
    weight = 6
